// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izyqgnvwdjthnxhlamcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6eXFnbnZ3ZGp0aG54aGxhbWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzM3MDcsImV4cCI6MjA1ODQwOTcwN30.qWCkrHOgcmltKLHJfJ0s5YgqDXsM1pgi_5uRdGKMd0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);